export const MOCK_TUTORS_RAW = [
  {
    id: "priya-m",
    name: "Priya Mehta",
    headline: "Physics & Further Maths · Imperial College London",
    bio: "Ex-exam board question writer. Specialises in turning mechanics anxiety into confidence for AQA and Edexcel students.",
    subjects: ["Physics", "Further_Maths"],
    boards: ["AQA", "Edexcel"],
    hourlyRate: 42,
    rating: 4.9,
    yearsExperience: 7,
  },
  {
    id: "daniel-osei",
    name: "Daniel Osei",
    headline: "Chemistry & Biology · Oxford, Biochemistry",
    bio: "Focuses on organic chemistry mechanisms and exam technique. Former OCR mark scheme moderator.",
    subjects: ["Chemistry", "Biology"],
    boards: ["OCR_A", "OCR_B"],
    hourlyRate: 38,
    rating: 5.0,
    yearsExperience: 5,
  },
  {
    id: "amelia-clarke",
    name: "Amelia Clarke",
    headline: "Mathematics & Computing · Cambridge, Computer Science",
    bio: "Loves making algorithms click. Runs weekly problem-solving clinics alongside 1:1 sessions.",
    subjects: ["Mathematics", "Computing"],
    boards: ["Edexcel", "AQA"],
    hourlyRate: 35,
    rating: 4.8,
    yearsExperience: 4,
  },
  {
    id: "yusuf-khan",
    name: "Yusuf Khan",
    headline: "Physics & Mathematics · Imperial College London",
    bio: "Specialist in particle physics and mechanics. Builds custom spec-mapped revision plans for every student.",
    subjects: ["Physics", "Mathematics"],
    boards: ["Edexcel", "CIE"],
    hourlyRate: 40,
    rating: 4.9,
    yearsExperience: 6,
  },
  {
    id: "sophie-nguyen",
    name: "Sophie Nguyen",
    headline: "Biology & Chemistry · UCL, Natural Sciences",
    bio: "Ex-NHS clinical scientist. Brings real-world context to A-Level biology and chemistry.",
    subjects: ["Biology", "Chemistry"],
    boards: ["AQA", "WJEC"],
    hourlyRate: 36,
    rating: 4.95,
    yearsExperience: 3,
  },
  {
    id: "marcus-webb",
    name: "Marcus Webb",
    headline: "Further Maths & Computing · Warwick, Mathematics",
    bio: "Competition mathematician. Great for students aiming for A* and STEP/MAT prep alongside A-Level.",
    subjects: ["Further_Maths", "Computing"],
    boards: ["OCR_A", "Edexcel"],
    hourlyRate: 45,
    rating: 4.85,
    yearsExperience: 8,
  },
];
